import { useState, useEffect, useRef } from 'react';
import Peer from 'simple-peer';

export const useWebRTC = (socket, role, localStream, partnerConnected) => {
  const [remoteStream, setRemoteStream] = useState(null);
  const [rtcStatus, setRtcStatus] = useState('disconnected'); // 'disconnected' | 'connecting' | 'connected' | 'error'
  const [rtcError, setRtcError] = useState(null);

  const peerRef = useRef(null);

  useEffect(() => {
    // We only initiate WebRTC setup if socket is active, the partner is connected,
    // and we have a local stream from the user.
    if (!socket || !partnerConnected || !localStream) {
      // Cleanup WebRTC connection if requirements are no longer met
      if (peerRef.current) {
        console.log('Cleaning up WebRTC peer connection due to missing stream/socket/partner');
        peerRef.current.destroy();
        peerRef.current = null;
      }
      setRemoteStream(null);
      setRtcStatus('disconnected');
      return;
    }

    console.log(`Setting up WebRTC connection. Role: ${role}, Socket ID: ${socket.id}`);
    setRtcStatus('connecting');

    try {
      const isLeader = role === 'leader';

      // Create a new simple-peer instance
      // The leader will initiate the WebRTC connection
      const peer = new Peer({
        initiator: isLeader,
        trickle: true, // Enable trickle ICE for faster and more resilient connections
        stream: localStream,
        config: {
          iceServers: [
            { urls: 'stun:stun.l.google.com:19302' },
            { urls: 'stun:stun1.l.google.com:19302' },
            { urls: 'stun:stun2.l.google.com:19302' },
          ],
        },
      });

      peerRef.current = peer;

      // Handle signal events generated by this peer
      peer.on('signal', (signalData) => {
        console.log('Local WebRTC signal generated, sending via socket...');
        socket.emit('signal', signalData);
      });

      // Handle remote stream event
      peer.on('stream', (stream) => {
        console.log('Received remote media stream!');
        setRemoteStream(stream);
        setRtcStatus('connected');
        setRtcError(null);
      });

      // Handle connection status events
      peer.on('connect', () => {
        console.log('WebRTC Peer connected successfully!');
        setRtcStatus('connected');
      });

      peer.on('error', (err) => {
        console.error('WebRTC Peer connection error:', err);
        setRtcStatus('error');
        setRtcError(`P2P Connection Error: ${err.message}`);
      });

      peer.on('close', () => {
        console.log('WebRTC Peer connection closed');
        setRtcStatus('disconnected');
        setRemoteStream(null);
      });

      // Listen to signaling data from the server
      const handleSignalMessage = (signalData) => {
        console.log('Received signaling message from remote peer');
        if (peer && !peer.destroyed) {
          peer.signal(signalData);
        }
      };

      socket.on('signal', handleSignalMessage);

      // Clean up on component unmount or state changes
      return () => {
        console.log('Cleaning up WebRTC signaling socket listener & peer');
        socket.off('signal', handleSignalMessage);
        if (peerRef.current) {
          peerRef.current.destroy();
          peerRef.current = null;
        }
        setRemoteStream(null);
        setRtcStatus('disconnected');
      };
    } catch (err) {
      console.error('Failed to create SimplePeer:', err);
      setRtcStatus('error');
      setRtcError(`Failed to initialize WebRTC: ${err.message}`);
    }
  }, [socket, role, localStream, partnerConnected]);

  return {
    remoteStream,
    rtcStatus,
    rtcError,
  };
};
