import { useState, useEffect, useRef } from 'react';
import Peer from 'simple-peer';

export const useWebRTC = (socket, role, localStream, partnerConnected) => {
  const [remoteStream, setRemoteStream] = useState(null);
  const [rtcStatus, setRtcStatus] = useState('disconnected'); // 'disconnected' | 'connecting' | 'connected' | 'error'
  const [rtcError, setRtcError] = useState(null);

  const peerRef = useRef(null);
  const pendingSignals = useRef([]);

  // 1. Independent Socket signaling listener to capture early signals
  useEffect(() => {
    if (!socket) return;

    const handleSignalMessage = (signalData) => {
      console.log('Socket received remote signaling data');
      if (peerRef.current && !peerRef.current.destroyed) {
        try {
          peerRef.current.signal(signalData);
        } catch (err) {
          console.error('Error signaling peer directly:', err);
        }
      } else {
        console.log('Peer connection not fully initialized yet. Queuing signal.');
        pendingSignals.current.push(signalData);
      }
    };

    socket.on('signal', handleSignalMessage);
    return () => {
      console.log('Cleaning up WebRTC signaling socket listener');
      socket.off('signal', handleSignalMessage);
    };
  }, [socket]);

  // 2. Peer connection setup lifecycle
  useEffect(() => {
    // We only initiate WebRTC setup if socket is active, the partner is connected,
    // and we have a local stream from the user.
    if (!socket || !partnerConnected || !localStream) {
      // Cleanup WebRTC connection if requirements are no longer met
      if (peerRef.current) {
        console.log('Cleaning up WebRTC peer connection due to missing stream/socket/partner');
        peerRef.current.destroy();
        peerRef.current = null;
      }
      setRemoteStream(null);
      setRtcStatus('disconnected');
      return;
    }

    console.log(`Setting up WebRTC connection. Role: ${role}, Socket ID: ${socket.id}`);
    setRtcStatus('connecting');

    try {
      const isLeader = role === 'leader';

      // Create a new simple-peer instance
      // ICE servers: multiple STUN + free public TURN relays
      // TURN servers are critical for users on the same Wi-Fi NAT or behind firewalls
      const iceServers = [
        { urls: 'stun:stun.l.google.com:19302' },
        { urls: 'stun:stun1.l.google.com:19302' },
        { urls: 'stun:stun2.l.google.com:19302' },
        { urls: 'stun:stun3.l.google.com:19302' },
        { urls: 'stun:stun4.l.google.com:19302' },
        // Free TURN relay (open-relay.metered.ca) - works reliably for photo booth use
        {
          urls: 'turn:openrelay.metered.ca:80',
          username: 'openrelayproject',
          credential: 'openrelayproject',
        },
        {
          urls: 'turn:openrelay.metered.ca:443',
          username: 'openrelayproject',
          credential: 'openrelayproject',
        },
        {
          urls: 'turn:openrelay.metered.ca:443?transport=tcp',
          username: 'openrelayproject',
          credential: 'openrelayproject',
        },
      ];

      const peer = new Peer({
        initiator: isLeader,
        trickle: true,
        stream: localStream,
        config: { iceServers },
      });

      peerRef.current = peer;

      // Process any early signals that arrived before the webcam finished initializing
      if (pendingSignals.current.length > 0) {
        console.log(`Applying ${pendingSignals.current.length} queued signaling packets to new peer`);
        pendingSignals.current.forEach((sig) => {
          try {
            peer.signal(sig);
          } catch (e) {
            console.error('Error applying queued signal:', e);
          }
        });
        pendingSignals.current = [];
      }

      // Handle signal events generated by this peer
      peer.on('signal', (signalData) => {
        console.log('Local WebRTC signal generated, sending via socket...');
        socket.emit('signal', signalData);
      });

      // Handle remote stream event
      peer.on('stream', (stream) => {
        console.log('Received remote media stream!');
        setRemoteStream(stream);
        setRtcStatus('connected');
        setRtcError(null);
      });

      // Handle connection status events
      peer.on('connect', () => {
        console.log('WebRTC Peer connected successfully!');
        setRtcStatus('connected');
      });

      peer.on('error', (err) => {
        console.error('WebRTC Peer connection error:', err);
        setRtcStatus('error');
        setRtcError(`P2P Connection Error: ${err.message}`);
      });

      peer.on('close', () => {
        console.log('WebRTC Peer connection closed');
        setRtcStatus('disconnected');
        setRemoteStream(null);
      });

      // Clean up on component unmount or state changes
      return () => {
        console.log('Cleaning up WebRTC peer');
        if (peerRef.current) {
          peerRef.current.destroy();
          peerRef.current = null;
        }
        setRemoteStream(null);
        setRtcStatus('disconnected');
      };
    } catch (err) {
      console.error('Failed to create SimplePeer:', err);
      setRtcStatus('error');
      setRtcError(`Failed to initialize WebRTC: ${err.message}`);
    }
  }, [socket, role, localStream, partnerConnected]);

  return {
    remoteStream,
    rtcStatus,
    rtcError,
  };
};
